import type { BusinessCardData } from '../types/card';
import { EXAMPLE_QR_CODE } from '../lib/demo-data';

const samples: BusinessCardData[] = [
  {
    firstName: 'Sarah',
    lastName: 'Chen',
    title: 'Chief Executive Officer',
    company: 'Nexus Dynamics',
    email: 'sarah.chen@nexusdyn.com',
    phone: '(415) 555-0142',
    website: 'www.nexusdyn.com',
    tagline: 'Innovation through collaboration',
    social: { linkedin: 'sarahchen' },
    logo: '/images/logos/nexus-dynamics.png',
    portrait: '/images/portraits/sarah-chen.png',
  },
  {
    firstName: 'Marcus',
    lastName: 'Rodriguez',
    title: 'Senior Software Engineer',
    company: 'Vertex Labs',
    email: 'marcus@vertexlabs.io',
    phone: '(512) 555-0198',
    website: 'vertexlabs.io',
    social: { github: 'mrodriguez', linkedin: 'marcusrodriguez' },
    logo: '/images/logos/vertex-labs.png',
    portrait: '/images/portraits/marcus-rodriguez.png',
  },
  {
    firstName: 'Emily',
    lastName: 'Whitfield',
    title: 'Creative Director',
    company: 'Prism Studio',
    email: 'emily@prismstudio.co',
    phone: '(323) 555-0167',
    website: 'prismstudio.co',
    social: { instagram: 'prismstudio' },
    logo: '/images/logos/prism-studio.png',
    portrait: '/images/portraits/emily-whitfield.png',
  },
  {
    firstName: 'Dr. James',
    lastName: 'Okafor',
    title: 'Cardiologist',
    company: 'Metro Heart Institute',
    credentials: 'MD, FACC',
    email: 'j.okafor@metroheart.org',
    phone: '(212) 555-0234',
    website: 'metroheart.org',
    logo: '/images/logos/metro-heart.png',
    portrait: '/images/portraits/james-okafor.png',
  },
  {
    firstName: 'Aisha',
    lastName: 'Patel',
    title: 'Attorney at Law',
    company: 'Patel & Associates',
    credentials: 'Esq.',
    email: 'aisha@patellaw.com',
    phone: '(617) 555-0189',
    website: 'patellaw.com',
    tagline: 'Trusted counsel for complex matters',
    logo: '/images/logos/patel-associates.png',
    portrait: '/images/portraits/aisha-patel.png',
  },
  {
    firstName: 'David',
    lastName: 'Kimura',
    title: 'Real Estate Agent',
    company: 'Summit Realty Group',
    email: 'david@summitrealty.com',
    phone: '(503) 555-0156',
    website: 'summitrealty.com',
    social: { instagram: 'davidkimura_realty' },
    logo: '/images/logos/summit-realty.png',
    portrait: '/images/portraits/sarah-chen.png',  // reuse
  },
  {
    firstName: 'Luna',
    lastName: 'Bergström',
    title: 'UX Designer',
    company: 'Pixel & Flow',
    email: 'luna@pixelflow.design',
    phone: '(206) 555-0123',
    website: 'pixelflow.design',
    social: { linkedin: 'lunabergstrom', twitter: 'lunadesigns' },
    logo: '/images/logos/pixel-flow.png',
    portrait: '/images/portraits/luna-bergstrom.png',
  },
  {
    firstName: 'Thomas',
    lastName: 'Williams',
    title: 'Financial Advisor',
    company: 'Meridian Wealth',
    credentials: 'CFP, CFA',
    email: 'thomas@meridianwealth.com',
    phone: '(312) 555-0178',
    website: 'meridianwealth.com',
    logo: '/images/logos/meridian-wealth.png',
    portrait: '/images/portraits/marcus-rodriguez.png',  // reuse
  },
  {
    firstName: 'Mei',
    lastName: 'Zhang',
    title: 'Head of Product',
    company: 'CloudScale',
    email: 'mei.zhang@cloudscale.dev',
    phone: '(650) 555-0145',
    website: 'cloudscale.dev',
    social: { linkedin: 'meizhang', twitter: 'meizh' },
    logo: '/images/logos/cloudscale.png',
    portrait: '/images/portraits/emily-whitfield.png',  // reuse
  },
  {
    firstName: 'Carlos',
    lastName: 'Mendez',
    title: 'Executive Chef',
    company: 'Tierra Restaurant',
    email: 'chef@tierrarestaurant.com',
    phone: '(305) 555-0167',
    website: 'tierrarestaurant.com',
    social: { instagram: 'chefcarlos' },
    tagline: 'Farm to table, heart to plate',
    logo: '/images/logos/tierra-restaurant.png',
    portrait: '/images/portraits/carlos-mendez.png',
  },
  {
    firstName: 'Rachel',
    lastName: 'Foster',
    title: 'Photographer',
    company: 'Foster Visuals',
    email: 'rachel@fostervisuals.com',
    phone: '(720) 555-0134',
    website: 'fostervisuals.com',
    social: { instagram: 'fostervisuals', twitter: 'rachelfoster' },
    logo: '/images/logos/foster-visuals.png',
    portrait: '/images/portraits/grace-obrien.png',  // reuse
  },
  {
    firstName: 'Nikolai',
    lastName: 'Petrov',
    title: 'Data Scientist',
    company: 'Quantum Analytics',
    email: 'nikolai@quantumanalytics.ai',
    phone: '(408) 555-0190',
    website: 'quantumanalytics.ai',
    social: { github: 'npetrov', linkedin: 'nikolaipetrov' },
    logo: '/images/logos/quantum-analytics.png',
    portrait: '/images/portraits/james-okafor.png',  // reuse
  },
  {
    firstName: 'Grace',
    lastName: "O'Brien",
    title: 'Marketing Director',
    company: 'Bloom Agency',
    email: 'grace@bloomagency.com',
    phone: '(646) 555-0112',
    website: 'bloomagency.com',
    social: { linkedin: 'graceobrien', twitter: 'bloomagency' },
    logo: '/images/logos/bloom-agency.png',
    portrait: '/images/portraits/grace-obrien.png',
  },
  {
    firstName: 'Hassan',
    lastName: 'Al-Rashid',
    title: 'Architect',
    company: 'Elevation Design Co.',
    credentials: 'AIA',
    email: 'hassan@elevationdesign.com',
    phone: '(202) 555-0156',
    website: 'elevationdesign.com',
    logo: '/images/logos/elevation-design.png',
    portrait: '/images/portraits/james-okafor.png',  // reuse
  },
  {
    firstName: 'Sophie',
    lastName: 'Laurent',
    title: 'Wellness Coach',
    company: 'Serenity Wellness',
    email: 'sophie@serenitywellness.co',
    phone: '(818) 555-0189',
    website: 'serenitywellness.co',
    social: { instagram: 'sophiewellness' },
    tagline: 'Balance your body, elevate your mind',
    logo: '/images/logos/serenity-wellness.png',
    portrait: '/images/portraits/aisha-patel.png',  // reuse
  },
  {
    firstName: 'Jordan',
    lastName: 'Taylor',
    title: 'DevOps Lead',
    company: 'InfraCore',
    email: 'jordan@infracore.io',
    phone: '(510) 555-0198',
    website: 'infracore.io',
    social: { github: 'jtaylor', linkedin: 'jordantaylor' },
    logo: '/images/logos/infracore.png',
    portrait: '/images/portraits/marcus-rodriguez.png',  // reuse
  },
  {
    firstName: 'Victoria',
    lastName: 'Novak',
    title: 'Interior Designer',
    company: 'Novak Interiors',
    email: 'victoria@novakinteriors.com',
    phone: '(404) 555-0167',
    website: 'novakinteriors.com',
    social: { instagram: 'novakinteriors' },
    logo: '/images/logos/novak-interiors.png',
    portrait: '/images/portraits/victoria-novak.png',
  },
  {
    firstName: 'Michael',
    lastName: 'Brennan',
    title: 'Managing Partner',
    company: 'Brennan Capital',
    credentials: 'MBA',
    email: 'michael@brennancap.com',
    phone: '(212) 555-0245',
    website: 'brennancap.com',
    social: { linkedin: 'michaelbrennan' },
    logo: '/images/logos/brennan-capital.png',
    portrait: '/images/portraits/james-okafor.png',  // reuse
  },
  {
    firstName: 'Yuki',
    lastName: 'Tanaka',
    title: 'Graphic Designer',
    company: 'Studio Yuki',
    email: 'yuki@studioyuki.com',
    phone: '(213) 555-0178',
    website: 'studioyuki.com',
    social: { instagram: 'studioyuki', twitter: 'yukidesigns' },
    logo: '/images/logos/soundwave-studios.png',  // reuse (music/creative)
    portrait: '/images/portraits/yuki-tanaka.png',
  },
  {
    firstName: 'Robert',
    lastName: 'Hughes',
    title: 'Civil Engineer',
    company: 'Apex Engineering',
    credentials: 'PE',
    email: 'robert@apexeng.com',
    phone: '(713) 555-0156',
    website: 'apexeng.com',
    logo: '/images/logos/infracore.png',  // reuse (engineering)
    portrait: '/images/portraits/marcus-rodriguez.png',  // reuse
  },
  {
    firstName: 'Priya',
    lastName: 'Sharma',
    title: 'Pediatrician',
    company: "Sunshine Children's Clinic",
    credentials: 'MD',
    email: 'dr.sharma@sunshinepeds.com',
    phone: '(858) 555-0134',
    website: 'sunshinepeds.com',
    logo: '/images/logos/metro-heart.png',  // reuse (medical)
    portrait: '/images/portraits/aisha-patel.png',  // reuse
  },
  {
    firstName: 'Alex',
    lastName: 'Rivera',
    title: 'Music Producer',
    company: 'Soundwave Studios',
    email: 'alex@soundwavestudios.com',
    phone: '(310) 555-0190',
    website: 'soundwavestudios.com',
    social: { instagram: 'soundwavestudios', twitter: 'alexrivera' },
    logo: '/images/logos/soundwave-studios.png',
    portrait: '/images/portraits/carlos-mendez.png',  // reuse
  },
  {
    firstName: 'Catherine',
    lastName: 'Moore',
    title: 'Tax Consultant',
    company: 'Moore & Associates CPA',
    credentials: 'CPA',
    email: 'catherine@moorecpa.com',
    phone: '(469) 555-0112',
    website: 'moorecpa.com',
    logo: '/images/logos/meridian-wealth.png',  // reuse (finance)
    portrait: '/images/portraits/emily-whitfield.png',  // reuse
  },
  {
    firstName: 'Liam',
    lastName: "O'Connor",
    title: 'Brewmaster',
    company: 'Heritage Brewing Co.',
    email: 'liam@heritagebrewing.com',
    phone: '(503) 555-0167',
    website: 'heritagebrewing.com',
    tagline: 'Crafted with tradition',
    social: { instagram: 'heritagebrewing' },
    logo: '/images/logos/heritage-brewing.png',
    portrait: '/images/portraits/carlos-mendez.png',  // reuse
  },
  {
    firstName: 'Diana',
    lastName: 'Vasquez',
    title: 'Veterinarian',
    company: 'Paws & Claws Animal Hospital',
    credentials: 'DVM',
    email: 'dr.vasquez@pawsclaws.vet',
    phone: '(602) 555-0189',
    website: 'pawsclaws.vet',
    logo: '/images/logos/serenity-wellness.png',  // reuse (care/wellness)
    portrait: '/images/portraits/victoria-novak.png',  // reuse
  },
];

export function getSampleData(index: number): BusinessCardData {
  const sample = samples[index % samples.length];
  // Inject example QR code if sample has none
  return {
    ...sample,
    qrCode: sample.qrCode ?? EXAMPLE_QR_CODE,
  };
}

export function getSampleCount() {
  return samples.length;
}
